version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_chatdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: chatdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
