# ===================================================================
# MAIN PRODUCTION CONFIGURATION
# This file is used when the application runs in Docker.
# ===================================================================

logging:
  level:
    org.springframework: WARN

spring:
  # --- Production Database (MySQL) ---
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/chatdb?createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:testuser}
    password: ${SPRING_DATASOURCE_PASSWORD:testpass}

  # --- JPA & Hibernate Configuration ---
  jpa:
    hibernate:
      # Use 'update' to update the schema based on entities without dropping data.
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # Use the modern dialect
    show-sql: true

  # --- Spring Boot Actuator Configuration ---
  management:
    endpoints:
      web:
        exposure:
          # Exposes the 'health' endpoint over HTTP
          include: "health"
        # Sets the base path for all actuator endpoints to match your NGINX proxy
        base-path: /api/actuator

  # --- Mail Configuration Stub ---
  mail:
    host: fakehost
    port: 587
    username: fake
    password: fake
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true