# MySQL Database

logging:
  level:
    org.springframework: WARN
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/chatdb?createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:testuser}
    password: ${SPRING_DATASOURCE_PASSWORD:testpass}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # <-- Tabellen automatisch generieren
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: fakehost
    port: 587
    username: fake
    password: fake
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# H2 Database connection

#logging:
#  level:
#    org.springframework: WARN
#---
#spring:
#  jpa:
#    database: H2
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        show_sql: false
#        use_sql_comments: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#  mail:
#    host: fakehost
#    port: 587
#    username: fake
#    password: fake
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true