logging:
  level:
    org.springframework: WARN

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatdb?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: testuser
    password: testpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: fakehost
    port: 587
    username: fake
    password: fake
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
