name: Build, Test and Deploy to University VM via Jump Host

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build the project using Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Copy files to VM via university jump host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: usershell.informatik.haw-hamburg.de
          username: infwax193
          key: ${{ secrets.JUMP_PRIVATE_KEY }}
          port: 22
          source: "./"
          target: "/home/guz/brieftaube-temp"
          rm: true
          timeout: 120s

      - name: Deploy to VM via jump host SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: usershell.informatik.haw-hamburg.de
          username: infwax193
          key: ${{ secrets.JUMP_PRIVATE_KEY }}
          script: |
            ssh -o StrictHostKeyChecking=no guz@141.22.11.71 '
              rm -rf ~/brieftaube &&
              mv ~/brieftaube-temp ~/brieftaube &&
              cd ~/brieftaube &&
              docker compose down &&
              docker compose build &&
              docker compose up -d
            '