version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: myapp-db
    restart: always
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_ROOT_PASSWORD: rootpw
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - myapp-network

volumes:
  mysql-data:

networks:
  myapp-network:
